### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by kenrubiooo** [xinntao/BasicSR#174]
Hi @xinntao,

I am trying to train with upscale of x2. However, I am still encountering this error

> RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3

1. What should be the paths in the dataroot_LQ in the .yml file? Are they supposed to be the generated directories after running the generate_mod_LR_bic.py code? I am always pointing to the `./srtoolbox/dataset/DIV2K/mod/DIV2K800_sub/LR/x2` and to the `./srtoolbox/dataset/DIV2K/mod/DIV2K100/LR/x2` directories for both training and validation datasets.

2. What should I place in the GT_size in the .yml file? Is it the `step` or the `crop_sz` parameter in the extract_subimgs_single.py? 

Thank you!

**Comment by kenrubiooo** [comment]
Aside from the .yml file, do we need to change some parameters or lines in the RRDBNet_arch.py? I am trying to root out the cause of the errors being encountered. Thank you!

**Comment by xinntao** [comment]
1. I think you are right. 
I attach a config file of X2 model of my own (change the txt to yml).
[train_SRResNetX2.txt](https://github.com/xinntao/BasicSR/files/3382645/train_SRResNetX2.txt)

2. Make sure your generated images are OK. And check whether they have the same number of images. 
For me, I use the following parameters. (Remembe to use differnet size for GT and LQ.)
```
GT:
crop_sz = 480
step = 240
thres_sz = 48
```
```
LQ:
crop_sz = 240
step = 120
thres_sz = 24
```
3. For RRDBNet,
You need to comment two lines in RRDBNet_arch.py

https://github.com/xinntao/BasicSR/blob/f9139136821a25c036a5beb835d2f5e1658fff56/codes/models/modules/RRDBNet_arch.py#L57
and 
https://github.com/xinntao/BasicSR/blob/f9139136821a25c036a5beb835d2f5e1658fff56/codes/models/modules/RRDBNet_arch.py#L69

**Comment by kenrubiooo** [comment]
>     1. I think you are right.
>        I attach a config file of X2 model of my own (change the txt to yml).
>        [train_SRResNetX2.txt](https://github.com/xinntao/BasicSR/files/3382645/train_SRResNetX2.txt)
> 
>     2. Make sure your generated images are OK. And check whether they have the same number of images.
>        For me, I use the following parameters. (Remembe to use differnet size for GT and LQ.)
> 
> 
> ```
> GT:
> crop_sz = 480
> step = 240
> thres_sz = 48
> ```
> 
> ```
> LQ:
> crop_sz = 240
> step = 120
> thres_sz = 24
> ```
> 
>     1. For RRDBNet,
>        You need to comment two lines in RRDBNet_arch.py
> 
> 
> https://github.com/xinntao/BasicSR/blob/f9139136821a25c036a5beb835d2f5e1658fff56/codes/models/modules/RRDBNet_arch.py#L57
> 
> and
> 
> https://github.com/xinntao/BasicSR/blob/f9139136821a25c036a5beb835d2f5e1658fff56/codes/models/modules/RRDBNet_arch.py#L69

This is much appreciated, @xinntao! I will update you on this training. I will comment and close if this goes well.

**Comment by kenrubiooo** [comment]
Hi @xinntao,

Here is what I did:
1. I cropped the DIV2K800 images using the `extract_subimgs_single.py` using these values:
```
    n_thread = 20
    crop_sz = 480
    step = 240
    thres_sz = 48
```

2. Then, I generated the HR, LR, and Bic folders for the DIV2K800_sub using the `generate_mod_LR_bic.py`

3. After that, I also created the lmdb files for the HR and LR images from the generated HR and LR folders.

4. I also did steps 1-2 for the DIV2K100 for the validation part in the .yml file.

Here is the train_ESRGANx2.yml file that I have. I am still having a CUDA out of memory error even though I have it running on a Titan RTX.

```
#### general settings
name: 003_RRDB_ESRGANx2_DIV2K
use_tb_logger: true
model: srgan
distortion: sr
scale: 2
gpu_ids: [1]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /home/ubuntu/srtoolbox/dataset/DIV2K/lmdb/DIV2K800_GTsub/HR.lmdb
    dataroot_LQ: /home/ubuntu/srtoolbox/dataset/DIV2K/lmdb/DIV2K800_GTsub/LR.lmdb

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 4
    GT_size: 480
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /home/ubuntu/srtoolbox/dataset/DIV2K/mod/DIV2K100_sub/HR/x2
    dataroot_LQ: /home/ubuntu/srtoolbox/dataset/DIV2K/mod/DIV2K100_sub/LR/x2

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: /home/wavemanila/srtoolbox/codes/esrgan/models/RRDB_ESRGAN_x4.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
```

Your help is much appreciated. Thank you!
