### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by IllidanS4** [xinntao/BasicSR#309]
How much video memory is expected to be allocated during training?

I have this config (tried to make it as minimalistic as possible for the example):
```yaml
# general settings
name: Test
model_type: ESRGANModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: ADV1
    type: PairedImageDataset
    dataroot_gt: "train_hq"
    dataroot_lq: "train_lq"
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 64
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: false
    num_worker_per_gpu: 1
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ADV2
    type: PairedImageDataset
    dataroot_gt: "val_hq"
    dataroot_lq: "val_lq"
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23

network_d:
  type: VGGStyleDiscriminator128
  num_in_ch: 3
  num_feat: 64

# path
path:
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
```

I would also try to decrease `batch_size_per_gpu`, but that leads to an error about size mismatch.

Running this immediately outputs this error:
```
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 6.00 GiB total capacity; 5.50 GiB already allocated; 46.90 MiB free; 1.84 MiB cached)
```
How much memory will this need? I tried to run this on the CPU and it needed about 16 GiB of RAM as well before crashing again due to low memory. Honestly I thought this would be a bit more manageable.

Full log [here](https://pastebin.com/raw/5h1WhqLy).
