### ISSUE TITLE
Hello, when I interrupt training and restart training from resume_state, learning_rate will not be updated.

### ISSUE THREAD

**Issue by yanghedada** [xinntao/BasicSR#327]
Hello, when I interrupt training and restart training from resume_state, learning_rate will not be updated.
When I was at the 3000 terminal, I started training at 3000. At 80,000, 12,000 learning rate will not change.
@xinntao 
```
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [80000, 120000, 150000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
```
