### ISSUE TITLE
Why EDVR use 'sum' as the loss reduction method?

### ISSUE THREAD

**Issue by hcwang95** [xinntao/BasicSR#359]
I am thinking using sum will let the loss magnitude change if we change the batch size or input resolution. Is there any reason to use 'sum' instead of 'mean'? Thanks a lot!

Reference config: [train_EDVR_M_x4_SR_REDS.yml](https://github.com/xinntao/BasicSR/blob/master/options/train/EDVR/train_EDVR_M_x4_SR_REDS.yml#L90-L93):
```
  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum
```
